language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - hhvm

env:
  - DEPS=lowest
  - DEPS=latest

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - phpenv config-rm xdebug.ini
  - if [[ $DEPS == 'lowest' ]]; then composer update --prefer-stable --no-interaction --prefer-lowest ; fi
  - if [[ $DEPS == 'latest' ]]; then composer update --prefer-stable --no-interaction ; fi

script:
  - vendor/bin/phpunit
